name: Dev GitHub Action

on:
  schedule:
    - cron: '*/30 * * * *' 
  
  workflow_dispatch:  # Allow manual triggering

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python cli.py

      - name: Make commit script executable
        run: chmod +x commit.sh

      - name: Commit and push changes
        run: ./commit.sh ${{ secrets.GITHUB_TOKEN }} "out/"
